name: Publish a new article

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - name: Create a new article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WORDS_COUNT: 300
          LANGUAGE: en
        run: npm run start
      - uses: stefanzweifel/git-auto-commit-action@v4
