name: Publish a new article

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - name: Create a new article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WORDS_COUNT: 400
          LANGUAGE: en
        run: npm run start
      - name: Commit and push
        env:
         CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
         CI_COMMIT_AUTHOR: Continuous Integration
        run: |
         git commit -a -m "Publish a new article"
         git push
